#!/usr/bin/env node
/**
 * Generate connector presets for every catalogue agent.
 * Writes packages/presets/src/generated-presets.ts
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const catalogDir = path.join(root, "data/catalog");
const outFile = path.join(root, "packages/presets/src/generated-presets.ts");

const PREFIX_RE = /^(us|eu|africa|asia|oceania)-/;

function marketOf(id, manifestMarket) {
  if (manifestMarket) return manifestMarket;
  const m = id.match(PREFIX_RE);
  return m ? m[1] : "za";
}

function bindingForTool(toolName, market) {
  const calendar = market === "eu" ? "m365_calendar" : "google_calendar";
  const handoff = market === "eu" ? "teams" : "slack";
  const t = toolName;

  if (t === "handoff_to_human") return { tool: t, connector: handoff };
  if (
    t.includes("book") ||
    t.includes("availability") ||
    t.includes("reschedule") ||
    t.includes("cancel") ||
    t === "check_table_availability" ||
    t === "check_calendar" ||
    t === "schedule_meeting" ||
    t === "set_reminder"
  ) {
    return { tool: t, connector: calendar };
  }
  if (t === "notify_team") return { tool: t, connector: handoff };
  if (t.includes("order") || t.includes("stock") || t === "get_order_status") {
    return { tool: t, connector: "shopify" };
  }
  if (
    t.includes("ticket") ||
    t.includes("lead") ||
    t.includes("capture") ||
    t.includes("onboarding")
  ) {
    return { tool: t, connector: "hubspot" };
  }
  if (t.includes("payslip") || t.includes("xero") || t.includes("documents")) {
    return { tool: t, connector: "xero" };
  }
  if (t.includes("place_order") || t.includes("payment") || t.includes("stripe")) {
    return { tool: t, connector: "stripe" };
  }
  if (t.includes("zendesk")) {
    return { tool: t, connector: "zendesk" };
  }
  return { tool: t, connector: "webhook" };
}

function phaseFor(tools) {
  const names = tools.map((t) => t.name || t);
  if (names.some((n) => /claim|payroll|place_order|payslip/i.test(n))) return 2;
  return 1;
}

const files = fs.readdirSync(catalogDir).filter((f) => f.endsWith(".agent.json"));
const presets = [];

// Consumer-line agents are hand-managed in packages/presets/src/index.ts (HAND_OVERRIDES) so
// their tools bind to real inbox/calendar connectors; skip them here to avoid a second copy.
const HAND_MANAGED = new Set(["personal-assistant"]);

for (const file of files.sort()) {
  const pkg = JSON.parse(fs.readFileSync(path.join(catalogDir, file), "utf8"));
  const id = pkg.manifest.id;
  if (HAND_MANAGED.has(id)) continue;
  const market = marketOf(id, pkg.manifest.market);
  const tools = Array.isArray(pkg.tools) ? pkg.tools : [];
  const toolNames = tools.map((t) => t.name || t).filter(Boolean);
  if (!toolNames.includes("handoff_to_human")) toolNames.push("handoff_to_human");

  const seen = new Set();
  const bindings = [];
  for (const name of toolNames) {
    if (seen.has(name)) continue;
    seen.add(name);
    bindings.push(bindingForTool(name, market));
  }

  presets.push({
    agentId: id,
    phase: phaseFor(tools),
    bindings,
  });
}

const lines = [];
lines.push(`/* AUTO-GENERATED by scripts/generate-presets.mjs — do not edit by hand */`);
lines.push(`import type { ToolBinding } from "@miai/connectors";`);
lines.push(``);
lines.push(`export interface GeneratedPreset {`);
lines.push(`  agentId: string;`);
lines.push(`  phase: 1 | 2;`);
lines.push(`  bindings: ToolBinding[];`);
lines.push(`}`);
lines.push(``);
lines.push(`export const GENERATED_PRESETS: GeneratedPreset[] = ${JSON.stringify(presets, null, 2)};`);
lines.push(``);

fs.writeFileSync(outFile, lines.join("\n"));
console.log(`Wrote ${presets.length} presets → ${outFile}`);
