// Auto-generated card one-liners for the business marketplace. One concise sentence per
// agent family describing what it does. Regenerate via the generate-card-blurbs workflow.
export const CARD_BLURBS: Record<string, string> = {
  "accounting-practice": "Answers front-desk filing questions and routes tax matters to a qualified accountant.",
  "admissions": "Answers entry-requirement questions and captures applications — routes appeals to a person.",
  "agency-studio": "Handles a creative studio's production requests and hands complex briefs to staff.",
  "agentic-commerce": "Searches merchant catalogs, checks inventory, generates purchase mandates with user consent, and executes zero-PAN tokenized checkouts.",
  "agri-advisory": "Answers agronomy programme questions and books advisory appointments for farmers.",
  "ai-coding-assistant": "Answers engineers' code questions grounded in repo docs — never invents secrets.",
  "airtime-bundles": "Explains airtime plans and bundles and captures purchase intent.",
  "bank-branch": "Answers branch banking questions and hands sensitive matters to staff.",
  "bi-analyst": "Explains published metrics and captures analysis requests — never invents numbers.",
  "bookkeeping": "Answers bookkeeping questions and logs client requests for the team.",
  "building-management": "Answers resident questions and logs building requests for property staff.",
  "case-management": "Answers matter-status questions and logs case documents — never gives legal advice.",
  "citizen-services": "Answers hours, forms, and where-to-go questions and routes case status.",
  "clinic-front-desk": "Answers non-clinical questions and books appointments — hands every clinical matter to staff.",
  "contract-review": "Captures contract-review intake and document checklists — escalates to an attorney.",
  "course-advisor": "Answers course questions and captures enrolment enquiries for a career college.",
  "credit-cards": "Answers card product questions and logs dispute intake — no card numbers in chat.",
  "customer-support": "Answers product and order questions and logs tickets for refunds and complaints.",
  "cybersecurity-desk": "Answers security policy questions and logs suspected incidents for the team.",
  "data-quality": "Answers data-quality questions and logs incidents — never silently fixes production data.",
  "delivery-tracking": "Tracks consignment status, confirms proof of delivery, and logs delivery exceptions.",
  "dental-front-desk": "Answers patient questions and books dental appointments, confirming before writing.",
  "dental-practice": "Handles patient enquiries and schedules visits for the practice.",
  "device-upgrades": "Explains eligible upgrade offers and captures upgrade intent from customers.",
  "devops-assistant": "Answers CI/CD and environment questions and logs incident tickets.",
  "documentation-assistant": "Drafts and locates internal docs from approved sources only.",
  "energy-operations": "Answers outage and service questions and logs work orders for customers.",
  "enterprise-connectivity": "Answers B2B connectivity questions and captures SD-WAN and fibre opportunities.",
  "events-venue": "Answers venue enquiries and books events, confirming details before writing.",
  "executive-assistant": "Manages scheduling and requests for the executive, confirming before acting.",
  "executive-dashboards": "Explains certified dashboard tiles and logs deep-dive requests from leaders.",
  "factory-operations": "Answers shift and line status questions and logs production exceptions.",
  "farm-operations": "Answers farm task and equipment questions and captures work logs — escalates safety immediately.",
  "fibre-support": "Answers install and outage questions and logs appointments — escalates network tickets.",
  "field-service": "Dispatches field jobs and logs service requests, confirming before writing.",
  "financial-reporting": "Answers close calendar and report pack questions and logs report requests.",
  "fleet-driver": "Answers fleet and driver questions and logs requests, confirming before writing.",
  "fraud-investigations": "Takes fraud reports and logs cases — never adjudicates liability or freezes accounts.",
  "front-desk": "Greets visitors and handles reception requests, confirming before writing.",
  "grant-stock-planner": "Plans grant-day stock levels and logs orders, confirming before writing.",
  "gym-membership": "Answers membership questions and captures sign-up requests, confirming before writing.",
  "home-services": "Books repair visits and dispatches jobs, routing urgent issues to a person.",
  "hotel-concierge": "Answers guest questions and arranges bookings, requests, and local recommendations.",
  "hotel-guest": "Handles guest requests, amenities, and stay questions during the visit.",
  "hr-helpdesk": "Answers staff policy questions and logs requests, escalating sensitive cases to HR.",
  "insurance-broker": "Explains cover options and captures quote details for a broker follow-up.",
  "insurance-claims": "Guides claimants through filing and logs claim details for adjusters.",
  "interview-scheduling": "Books candidate interview slots and confirms times before writing anything.",
  "investment-advisor": "Captures intake and risk answers for an advisor, never giving personalized advice.",
  "it-helpdesk": "Answers common IT questions and logs tickets, escalating complex issues to staff.",
  "law-firm-intake": "Captures new-matter details and routes prospective clients to the right attorney.",
  "learning-development": "Answers course questions and logs enrollments, never inventing completion records.",
  "legal-research": "Captures research requests for attorneys, never delivering opinions or invented citations.",
  "licensing": "Answers licence questions and logs application details for review.",
  "loan-prequalifier": "Collects applicant details and checks basic loan eligibility before a human reviews.",
  "loyalty-rewards": "Answers rewards questions and logs point redemptions and member enrollments.",
  "maintenance-desk": "Logs work orders and checks parts, escalating safety issues immediately.",
  "marketing-assistant": "Drafts campaign content and captures marketing requests, confirming before anything is saved.",
  "media-content-desk": "Answers content rights questions and logs clearance requests, never inventing licence grants.",
  "mobile-money": "Answers account questions and captures transaction requests, routing sensitive cases to staff.",
  "mortgage-advisor": "Answers product questions and captures soft pre-qualification details, never a credit decision.",
  "municipality-desk": "Answers rates and permit questions and logs service requests.",
  "network-faults": "Captures fault reports and creates triage tickets for the team.",
  "onboarding-buddy": "Guides new hires through onboarding steps and confirms before writing.",
  "order-tracking": "Answers order-status questions and routes exceptions to a human.",
  "passport-visa": "Explains passport and visa processes and logs appointment intakes.",
  "payment-disputes": "Captures card and payment dispute details and confirms before filing.",
  "payroll-queries": "Answers payroll questions and logs queries for the team.",
  "performance-reviews": "Explains review cycles and schedules performance review sessions.",
  "pharmacy": "Answers pharmacy questions and routes clinical matters to a pharmacist.",
  "policy-compliance": "Answers policy questions and logs compliance requests for review.",
  "procurement": "Answers procurement questions and captures purchase requests for approval.",
  "product-finder": "Helps shoppers find the right product and answers questions.",
  "production-planning": "Answers scheduling questions and logs production change requests.",
  "prompt-engineering": "Helps teams design prompts and captures prompt-review requests.",
  "property-enquiries": "Answers property listing questions and captures buyer enquiries.",
  "qa-testing": "Answers test-case questions and logs defect reports for triage.",
  "quality-assurance": "Captures nonconformance reports and routes decisions to a reviewer.",
  "recruitment": "Answers role questions and captures job applications for review.",
  "remittance": "Answers money-transfer questions and confirms details before logging.",
  "rental-enquiries": "Answers rental listing questions and captures tenant enquiries.",
  "restaurant-takeaway": "Answers menu and allergen questions, books tables, and captures collection or delivery orders.",
  "returns-exchanges": "Guides shoppers through returns and exchanges, logging each request for staff.",
  "sales-forecasting": "Answers pipeline forecast questions and logs forecast adjustments — never invents quota attainment.",
  "sales-qualifier": "Screens inbound leads, qualifies fit, and routes promising prospects to sales reps.",
  "salon-booking": "Books haircuts and treatments, checks availability, and handles reschedules.",
  "security-incident": "Captures security incident reports, triages severity, and escalates critical ones immediately.",
  "sim-registration": "Captures SIM registration details and confirms before submitting to the register.",
  "social-services": "Answers benefits programme questions and captures referrals — never decides eligibility.",
  "spaza-merchant": "Answers stock and price questions and captures orders for the corner store.",
  "stock-availability": "Checks product stock and availability and confirms what customers can buy.",
  "student-helpdesk": "Answers student questions and logs requests for the college front office.",
  "tax-office": "Answers filing deadline and document questions — never gives tax advice.",
  "tour-activity": "Answers tour questions, checks availability, and books activities for guests.",
  "trades-receptionist": "Books plumbing, electrical, and building jobs and routes emergencies to a human.",
  "travel-desk": "Answers travel questions and captures booking requests for the team.",
  "utility-billing": "Answers billing and account questions and logs meter and payment queries.",
  "vas-concierge": "Answers gift card and airtime questions and captures purchase requests.",
  "veterinary": "Books vet appointments and answers pet care questions for the clinic.",
  "warehouse-operations": "Answers pick, pack, and location questions and logs exceptions for staff.",
  "wealth-management": "Answers wealth desk questions and books meetings — never recommends investments.",
};
